name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *' # every one minute
  push:
    branches:
      - main
jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: SuperteamDAO
          base: main
          head: main
