name: Sync Fork

on:
  push:
    branches: ["*"]

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: SuperteamDAO
          base: main
          head: main
